package com.karoliinamultas.parliamentmembersproject

import androidx.room.Entity
import androidx.room.PrimaryKey

fun main() {
    val p = ParliamentMembersData.members
    // try out map, filter etc. with collection p, for example:
    // - how many MPs are there in party ps?
    // - how many MPs in party kesk are there in constituency Uusimaa?
    // - how many parties are in the government? (parties with at least one MP who is a minister)
    // - what is the (approximate) average age of MPs is party kok
    // - create a map where constituency is the key and MP the value
    //      * print a list of constituencies and their # of MPs
    //      * print constituencies in order of # of MPs
}
@Entity (tableName = "politician_table")
data class MemberOfParliament (
    @PrimaryKey
    val personNumber: Int,
    val seatNumber: Int = 0,
    val last: String,
    val first: String,
    val party: String,
    val minister: Boolean = false,
    val picture: String = "",
    val twitter: String = "",
    val bornYear: Int = 0,
    val constituency: String = ""
)

object ParliamentMembersData {
    val members = listOf(
        MemberOfParliament(
            personNumber = 1467,
            seatNumber = 64,
            last = "Huru",
            first = "Petri",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Huru-Petri-web-v0003-1467.jpg",
            twitter = "https://twitter.com/HuruPetri",
            bornYear = 1966,
            constituency = "Satakunta",
        ),
        MemberOfParliament(
            personNumber = 1415,
            seatNumber = 168,
            last = "Kemppi",
            first = "Hilkka",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Kemppi-Hilkka-web-v6614-1415.JPG",
            twitter = "",
            bornYear = 1988,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1394,
            seatNumber = 197,
            last = "Keto-Huovinen",
            first = "Pihla",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Keto-Huovinen-Pihla-web-V7487-1394.jpg",
            twitter = "",
            bornYear = 1974,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 464,
            seatNumber = 20,
            last = "Kiljunen",
            first = "Kimmo",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Kiljunen-Kimmo-web-v7760-464.JPG",
            twitter = "",
            bornYear = 1951,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 791,
            seatNumber = 21,
            last = "Kiljunen",
            first = "Anneli",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Kiljunen-Anneli-web-v8182-791.JPG",
            twitter = "",
            bornYear = 1957,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1432,
            seatNumber = 199,
            last = "Kilpi",
            first = "Marko",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Kilpi-Marko-web-v7341-1432.JPG",
            twitter = "",
            bornYear = 1969,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1453,
            seatNumber = 140,
            last = "Kinnunen",
            first = "Mikko",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Kinnunen-Mikko-web-v6707-1453.JPG",
            twitter = "",
            bornYear = 1967,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1137,
            seatNumber = 85,
            last = "Kiuru",
            first = "Pauli",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Kiuru-Pauli-web-v8122-1137.JPG",
            twitter = "",
            bornYear = 1962,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1384,
            seatNumber = 128,
            last = "Kivelä",
            first = "Mai",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Kivela-Mai-web-v7260-1384.JPG",
            twitter = "https://twitter.com/MaiKivela",
            bornYear = 1982,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1340,
            seatNumber = 108,
            last = "Kulmuni",
            first = "Katri",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Kulmuni-Katri-web-v7250-1340.JPG",
            twitter = "",
            bornYear = 1987,
            constituency = "Lappi",
        ),
        MemberOfParliament(
            personNumber = 963,
            seatNumber = 39,
            last = "Kyllönen",
            first = "Merja",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Kyllonen-Merja-web-v6956-963.JPG",
            twitter = "",
            bornYear = 1977,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1144,
            seatNumber = 70,
            last = "Kymäläinen",
            first = "Suna",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Kymalainen-Suna-web-v8219-1144.JPG",
            twitter = "",
            bornYear = 1976,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1348,
            seatNumber = 111,
            last = "Kärnä",
            first = "Mikko",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Karna-Mikko-web-v6604-1348.JPG",
            twitter = "",
            bornYear = 1980,
            constituency = "Lappi",
        ),
        MemberOfParliament(
            personNumber = 1446,
            seatNumber = 189,
            last = "Könttä",
            first = "Joonas",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Kontta-Joonas-web-v6927-1446.JPG",
            twitter = "",
            bornYear = 1989,
            constituency = "Keski-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1426,
            seatNumber = 122,
            last = "Laakso",
            first = "Sheikki",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Laakso-Kristian-Sheikki-web-v7803-1426.JPG",
            twitter = "",
            bornYear = 1968,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1379,
            seatNumber = 177,
            last = "Laiho",
            first = "Mia",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Laiho-Mia-web-v8407-1379.JPG",
            twitter = "",
            bornYear = 1969,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1343,
            seatNumber = 115,
            last = "Laukkanen",
            first = "Antero",
            party = "kd",
            minister = false,
            picture = "attachment/member/pictures/Laukkanen-Antero-web-v6584-1343.jpg",
            twitter = "",
            bornYear = 1958,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1344,
            seatNumber = 63,
            last = "Lehto",
            first = "Rami",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Lehto-Rami-web-v6756-1344.JPG",
            twitter = "",
            bornYear = 1973,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1279,
            seatNumber = 149,
            last = "Valtonen",
            first = "Elina",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Lepomaki-Elina-web-v8095-1279.JPG",
            twitter = "",
            bornYear = 1981,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1306,
            seatNumber = 83,
            last = "Adlercreutz",
            first = "Anders",
            party = "r",
            minister = false,
            picture = "attachment/member/pictures/Adlercreutz-Anders-web-v7972-1306.JPG",
            twitter = "https://twitter.com/adleande",
            bornYear = 1970,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1452,
            seatNumber = 167,
            last = "Aittakumpu",
            first = "Pekka",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Aittakumpu-Pekka-web-v7125-1452.JPG",
            twitter = "https://twitter.com/PAittakumpu",
            bornYear = 1981,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 914,
            seatNumber = 24,
            last = "Alanko-Kahiluoto",
            first = "Outi",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Alanko-Kahiluoto-Outi-web-v7158-914.JPG",
            twitter = "https://twitter.com/outialanko",
            bornYear = 1966,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1310,
            seatNumber = 66,
            last = "Andersson",
            first = "Li",
            party = "vas",
            minister = true,
            picture = "attachment/member/pictures/Andersson-Li-web-v8045-1310.JPG",
            twitter = "",
            bornYear = 1987,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1434,
            seatNumber = 151,
            last = "Antikainen",
            first = "Sanna",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Antikainen-Sanna-web-v6546-1434.JPG",
            twitter = "https://twitter.com/SannaAntikainen",
            bornYear = 1988,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 917,
            seatNumber = 2,
            last = "Arhinmäki",
            first = "Paavo",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Arhinmaki-Paavo-web-v7598-917.JPG",
            twitter = "https://twitter.com/paavoarhinmaki",
            bornYear = 1976,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1089,
            seatNumber = 174,
            last = "Autto",
            first = "Heikki",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Autto-Heikki-web-v8381-1089.JPG",
            twitter = "https://twitter.com/heikkiautto",
            bornYear = 1984,
            constituency = "Lappi",
        ),
        MemberOfParliament(
            personNumber = 1406,
            seatNumber = 144,
            last = "Bergqvist",
            first = "Sandra",
            party = "r",
            minister = false,
            picture = "attachment/member/pictures/Bergqvist-Sandra-web-v7186-1406.JPG",
            twitter = "https://twitter.com/SandraBergq",
            bornYear = 1980,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 351,
            seatNumber = 10,
            last = "Biaudet",
            first = "Eva",
            party = "r",
            minister = false,
            picture = "attachment/member/pictures/Biaudet-Eva-web-v7586-351.JPG",
            twitter = "https://twitter.com/EvaBiaudet",
            bornYear = 1961,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 923,
            seatNumber = 53,
            last = "Blomqvist",
            first = "Thomas",
            party = "r",
            minister = true,
            picture = "attachment/member/pictures/Blomqvist-Thomas-web-v7897-923.JPG",
            twitter = "https://twitter.com/ThomasBlomqvis7",
            bornYear = 1965,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1093,
            seatNumber = 14,
            last = "Eerola",
            first = "Juho",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Eerola-Juho-web-v8160-1093.JPG",
            twitter = "https://twitter.com/EerolaJuho",
            bornYear = 1965,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1094,
            seatNumber = 31,
            last = "Eestilä",
            first = "Markku",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Eestila-Markku-web-v7396-1094.JPG",
            twitter = "",
            bornYear = 1956,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1401,
            seatNumber = 76,
            last = "Elo",
            first = "Tiina",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Elo-Tiina-web-v7107-1401.jpg",
            twitter = "https://twitter.com/TiinaElo",
            bornYear = 1971,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1096,
            seatNumber = 16,
            last = "Elomaa",
            first = "Ritva",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Elomaa-Ritva-web-v7770-1096.JPG",
            twitter = "",
            bornYear = 1955,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1430,
            seatNumber = 130,
            last = "Eskelinen",
            first = "Seppo",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Eskelinen-Seppo-web-v8003-1430.JPG",
            twitter = "",
            bornYear = 1960,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 778,
            seatNumber = 54,
            last = "Essayah",
            first = "Sari",
            party = "kd",
            minister = false,
            picture = "attachment/member/pictures/Essayah-Sari-web-v8260-778.JPG",
            twitter = "https://twitter.com/SariEssayah",
            bornYear = 1967,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 451,
            seatNumber = 3,
            last = "Filatov",
            first = "Tarja",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Filatov-Tarja-web-v7788-451.JPG",
            twitter = "https://twitter.com/TarjaFilatov",
            bornYear = 1964,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1445,
            seatNumber = 105,
            last = "Forsgrén",
            first = "Bella",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Forsgren-Bella-web-v7225-1445.JPG",
            twitter = "",
            bornYear = 1992,
            constituency = "Keski-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1100,
            seatNumber = 88,
            last = "Grahn-Laasonen",
            first = "Sanni",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Grahn-Laasonen-Sanni-web-v8106-1100.JPG",
            twitter = "",
            bornYear = 1983,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 116,
            seatNumber = 4,
            last = "Gustafsson",
            first = "Jukka",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Gustafsson-Jukka-web-v7715-116.JPG",
            twitter = "",
            bornYear = 1947,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 926,
            seatNumber = 46,
            last = "Guzenina",
            first = "Maria",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Guzenina-Maria-web-v7746-926.JPG",
            twitter = "",
            bornYear = 1969,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 118,
            seatNumber = 6,
            last = "Haavisto",
            first = "Pekka",
            party = "vihr",
            minister = true,
            picture = "attachment/member/pictures/Haavisto-Pekka-web-v7627-118.JPG",
            twitter = "https://twitter.com/Haavisto",
            bornYear = 1958,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1109,
            seatNumber = 60,
            last = "Halla-aho",
            first = "Jussi",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Halla-aho-Jussi-web-v7607-1109.JPG",
            twitter = "https://twitter.com/Halla_aho",
            bornYear = 1971,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1326,
            seatNumber = 101,
            last = "Harakka",
            first = "Timo",
            party = "sd",
            minister = true,
            picture = "attachment/member/pictures/Harakka-Timo-web-v7755-1326.jpg",
            twitter = "",
            bornYear = 1962,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1385,
            seatNumber = 106,
            last = "Harjanne",
            first = "Atte",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Harjanne-Atte-web-v7646-1385.JPG",
            twitter = "https://twitter.com/AtteHarjanne",
            bornYear = 1984,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1328,
            seatNumber = 190,
            last = "Harkimo",
            first = "Harry",
            party = "liik",
            minister = false,
            picture = "attachment/member/pictures/Harkimo-Harry-web-v7222-1328.jpg",
            twitter = "",
            bornYear = 1953,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 363,
            seatNumber = 7,
            last = "Hassi",
            first = "Satu",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Hassi-Satu-web-v7696-363.jpg",
            twitter = "",
            bornYear = 1951,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 938,
            seatNumber = 52,
            last = "Heikkinen",
            first = "Hannakaisa",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Heikkinen-Hannakaisa-web-v8270-938.JPG",
            twitter = "",
            bornYear = 1974,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1454,
            seatNumber = 192,
            last = "Heikkinen",
            first = "Janne",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Heikkinen-Janne-web-v7284-1454.JPG",
            twitter = "",
            bornYear = 1990,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 967,
            seatNumber = 55,
            last = "Heinonen",
            first = "Timo",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Heinonen-Timo-web-v7279-967.JPG",
            twitter = "",
            bornYear = 1975,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1390,
            seatNumber = 159,
            last = "Heinäluoma",
            first = "Eveliina",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Heinaluoma-Eveliina-web-v6915-1390.JPG",
            twitter = "https://twitter.com/eveheinaluoma",
            bornYear = 1988,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 941,
            seatNumber = 29,
            last = "Henriksson",
            first = "Anna-Maja",
            party = "r",
            minister = true,
            picture = "attachment/member/pictures/Henriksson-Anna-Maja-web-v8298-941.JPG",
            twitter = "",
            bornYear = 1964,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1424,
            seatNumber = 107,
            last = "Holopainen",
            first = "Hanna",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Holopainen-Hanna-web-v6647-1424.JPG",
            twitter = "",
            bornYear = 1976,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1386,
            seatNumber = 135,
            last = "Holopainen",
            first = "Mari",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Holopainen-Mari-web-v1581-1386.jpg",
            twitter = "https://twitter.com/mariholopainen",
            bornYear = 1981,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1383,
            seatNumber = 97,
            last = "Honkasalo",
            first = "Veronika",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Honkasalo-Veronika-web-v7460-1383.JPG",
            twitter = "https://twitter.com/veronikahonka",
            bornYear = 1975,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1331,
            seatNumber = 112,
            last = "Honkonen",
            first = "Petri",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Honkonen-Petri-web-v7089-1331.JPG",
            twitter = "",
            bornYear = 1987,
            constituency = "Keski-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1402,
            seatNumber = 136,
            last = "Hopsu",
            first = "Inka",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Hopsu-Inka-web-v7147-1402.JPG",
            twitter = "",
            bornYear = 1976,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1433,
            seatNumber = 142,
            last = "Huttunen",
            first = "Hanna",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Huttunen-Hanna-web-v6967-1433.JPG",
            twitter = "",
            bornYear = 1969,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1403,
            seatNumber = 137,
            last = "Hyrkkö",
            first = "Saara",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Hyrkko-Saara-web-v7074-1403.JPG",
            twitter = "",
            bornYear = 1987,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1334,
            seatNumber = 175,
            last = "Häkkänen",
            first = "Antti",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Hakkanen-Antti-web-v8170-1334.JPG",
            twitter = "",
            bornYear = 1985,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1276,
            seatNumber = 67,
            last = "Hänninen",
            first = "Katja",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Hanninen-Katja-web-v7706-1276.JPG",
            twitter = "",
            bornYear = 1980,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1421,
            seatNumber = 195,
            last = "Ikonen",
            first = "Anna-Kaisa",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Ikonen-Anna-Kaisa-web-v7294-1421.JPG",
            twitter = "",
            bornYear = 1977,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1122,
            seatNumber = 37,
            last = "Immonen",
            first = "Olli",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Immonen-Olli-web-v7393-1122.JPG",
            twitter = "",
            bornYear = 1986,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1056,
            seatNumber = 58,
            last = "Jokinen",
            first = "Kalle",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Jokinen-Kalle-web-v7995-1056.JPG",
            twitter = "",
            bornYear = 1961,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1409,
            seatNumber = 154,
            last = "Junnila",
            first = "Vilhelm",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Junnila-Vilhelm-web-v7455-1409.JPG",
            twitter = "",
            bornYear = 1982,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1455,
            seatNumber = 90,
            last = "Juuso",
            first = "Kaisa",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Juuso-Kaisa-web-v7197-1455.JPG",
            twitter = "",
            bornYear = 1960,
            constituency = "Lappi",
        ),
        MemberOfParliament(
            personNumber = 1129,
            seatNumber = 59,
            last = "Juvonen",
            first = "Arja",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Juvonen-Arja-web-v7378-1129.JPG",
            twitter = "",
            bornYear = 1967,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 930,
            seatNumber = 25,
            last = "Järvinen",
            first = "Heli",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Jarvinen-Heli-web-v1527-930.jpg",
            twitter = "",
            bornYear = 1960,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 772,
            seatNumber = 50,
            last = "Kaikkonen",
            first = "Antti",
            party = "kesk",
            minister = true,
            picture = "attachment/member/pictures/Kaikkonen-Antti-web-v7924-772.JPG",
            twitter = "",
            bornYear = 1974,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1412,
            seatNumber = 141,
            last = "Kalli",
            first = "Eeva",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Kalli-Eeva-web-v6778-1412.JPG",
            twitter = "https://twitter.com/Eeva_Kalli",
            bornYear = 1981,
            constituency = "Satakunta",
        ),
        MemberOfParliament(
            personNumber = 953,
            seatNumber = 49,
            last = "Kalmari",
            first = "Anne",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Kalmari-Anne-web-v8152-953.JPG",
            twitter = "",
            bornYear = 1968,
            constituency = "Keski-Suomi",
        ),
        MemberOfParliament(
            personNumber = 170,
            seatNumber = 12,
            last = "Kanerva",
            first = "Ilkka",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Kanerva-Ilkka-web-v8029-170.JPG",
            twitter = "",
            bornYear = 1948,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 175,
            seatNumber = 15,
            last = "Kankaanniemi",
            first = "Toimi",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Kankaanniemi_Toimi_web-v0747-175.jpg",
            twitter = "",
            bornYear = 1950,
            constituency = "Keski-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1133,
            seatNumber = 71,
            last = "Kari",
            first = "Mika",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Kari-Mika-web-v8424-1133.JPG",
            twitter = "",
            bornYear = 1967,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1336,
            seatNumber = 75,
            last = "Kari",
            first = "Emma",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Kari-Emma-web-v7100-1336.JPG",
            twitter = "https://twitter.com/EmmaKari",
            bornYear = 1983,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1135,
            seatNumber = 116,
            last = "Kauma",
            first = "Pia",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Kauma-Pia-web-v7723-1135.JPG",
            twitter = "",
            bornYear = 1966,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1425,
            seatNumber = 194,
            last = "Kaunisto",
            first = "Ville",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Kaunisto-Ville-web-v7437-1425.JPG",
            twitter = "",
            bornYear = 1982,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1444,
            seatNumber = 129,
            last = "Kautto",
            first = "Juho",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Kautto-Juho-web-v7334-1444.JPG",
            twitter = "",
            bornYear = 1971,
            constituency = "Keski-Suomi",
        ),
        MemberOfParliament(
            personNumber = 779,
            seatNumber = 26,
            last = "Kiviranta",
            first = "Esko",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Kiviranta-Esko-web-v8054-779.JPG",
            twitter = "",
            bornYear = 1950,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1155,
            seatNumber = 17,
            last = "Kontula",
            first = "Anna",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Kontula-Anna-web-v8081-1155.JPG",
            twitter = "",
            bornYear = 1977,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1341,
            seatNumber = 51,
            last = "Kurvinen",
            first = "Antti",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Kurvinen-Antti-web-v8282-1341.JPG",
            twitter = "",
            bornYear = 1986,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1398,
            seatNumber = 158,
            last = "Kvarnström",
            first = "Johan",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Kvarnstrom-Johan-web-v7810-1398.JPG",
            twitter = "",
            bornYear = 1986,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 582,
            seatNumber = 9,
            last = "Leppä",
            first = "Jari",
            party = "kesk",
            minister = true,
            picture = "attachment/member/pictures/Leppa-Jari-web-v7179-582.JPG",
            twitter = "",
            bornYear = 1959,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1408,
            seatNumber = 134,
            last = "Lindén",
            first = "Aki",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Linden-Aki-web-v7816-1408.JPG",
            twitter = "",
            bornYear = 1952,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1147,
            seatNumber = 44,
            last = "Lindtman",
            first = "Antti",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Lindtman-Antti-web-v7880-1147.JPG",
            twitter = "",
            bornYear = 1982,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 583,
            seatNumber = 27,
            last = "Lintilä",
            first = "Mika",
            party = "kesk",
            minister = true,
            picture = "attachment/member/pictures/Lintila-Mika-web-v7201-583.JPG",
            twitter = "",
            bornYear = 1966,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1149,
            seatNumber = 80,
            last = "Lohi",
            first = "Markus",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Lohi-Markus-web-v6627-1149.JPG",
            twitter = "",
            bornYear = 1972,
            constituency = "Lappi",
        ),
        MemberOfParliament(
            personNumber = 1399,
            seatNumber = 127,
            last = "Lohikoski",
            first = "Pia",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Lohikoski-Pia-web-v8359-1399.JPG",
            twitter = "",
            bornYear = 1977,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1410,
            seatNumber = 153,
            last = "Lundén",
            first = "Mikko",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Lunden-Mikko-web-v6636-1410.JPG",
            twitter = "",
            bornYear = 1979,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1428,
            seatNumber = 160,
            last = "Malm",
            first = "Niina",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Malm-Niina-web-v8361-1428.JPG",
            twitter = "",
            bornYear = 1982,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1297,
            seatNumber = 100,
            last = "Marin",
            first = "Sanna",
            party = "sd",
            minister = true,
            picture = "attachment/member/pictures/Marin-Sanna-web-v8134-1297.JPG",
            twitter = "",
            bornYear = 1985,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1397,
            seatNumber = 162,
            last = "al-Taee",
            first = "Hussein",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/al-Taee-Hussein-web-v7834-1397.JPG",
            twitter = "",
            bornYear = 1983,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 970,
            seatNumber = 102,
            last = "Asell",
            first = "Marko",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Asell-Marko-web-v7546-970.JPG",
            twitter = "https://twitter.com/markoasell",
            bornYear = 1970,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1443,
            seatNumber = 131,
            last = "Berg",
            first = "Kim",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Berg-Kim-web-v7560-1443.JPG",
            twitter = "",
            bornYear = 1974,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1099,
            seatNumber = 72,
            last = "Eloranta",
            first = "Eeva-Johanna",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Eloranta-Eeva-Johanna-web-v6995-1099.JPG",
            twitter = "https://twitter.com/elorantaeevajoh",
            bornYear = 1966,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 538,
            seatNumber = 19,
            last = "Haatainen",
            first = "Tuula",
            party = "sd",
            minister = true,
            picture = "attachment/member/pictures/Haatainen-Tuula-web-v7638-538.JPG",
            twitter = "https://twitter.com/TuulaHaatainen",
            bornYear = 1960,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 797,
            seatNumber = 28,
            last = "Hoskonen",
            first = "Hannu",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Hoskonen-Hannu-web-v7063-797.JPG",
            twitter = "",
            bornYear = 1957,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1468,
            seatNumber = 166,
            last = "Kettunen",
            first = "Tuomas",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Kettunen-Tuomas-web-v1012-1468.jpg",
            twitter = "",
            bornYear = 1988,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 960,
            seatNumber = 42,
            last = "Kiuru",
            first = "Krista",
            party = "sd",
            minister = true,
            picture = "attachment/member/pictures/Kiuru-Krista-web-v7944-960.JPG",
            twitter = "",
            bornYear = 1974,
            constituency = "Satakunta",
        ),
        MemberOfParliament(
            personNumber = 1442,
            seatNumber = 138,
            last = "Kivisaari",
            first = "Pasi",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Kivisaari-Pasi-web-v6729-1442.JPG",
            twitter = "",
            bornYear = 1971,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1391,
            seatNumber = 152,
            last = "Koponen",
            first = "Ari",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Koponen-Ari-web-v6691-1391.JPG",
            twitter = "",
            bornYear = 1982,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1404,
            seatNumber = 163,
            last = "Koponen",
            first = "Noora",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Koponen-Noora-web-v5744-1404.jpg",
            twitter = "",
            bornYear = 1983,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1142,
            seatNumber = 87,
            last = "Kopra",
            first = "Jukka",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Kopra-Jukka-web-v8188-1142.JPG",
            twitter = "",
            bornYear = 1967,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1413,
            seatNumber = 94,
            last = "Koskela",
            first = "Jari",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Koskela-Jari-web-v6878-1413.JPG",
            twitter = "",
            bornYear = 1956,
            constituency = "Satakunta",
        ),
        MemberOfParliament(
            personNumber = 358,
            seatNumber = 23,
            last = "Koskinen",
            first = "Johannes",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Koskinen-Johannes-web-v6839-358.JPG",
            twitter = "",
            bornYear = 1954,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1338,
            seatNumber = 110,
            last = "Kosonen",
            first = "Hanna",
            party = "kesk",
            minister = true,
            picture = "attachment/member/pictures/Kosonen-Hanna-web-v6940-1338.JPG",
            twitter = "",
            bornYear = 1976,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1448,
            seatNumber = 96,
            last = "Kotiaho",
            first = "Jouni",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Kotiaho-Jouni-web-v6885-1448.JPG",
            twitter = "",
            bornYear = 1958,
            constituency = "Keski-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1389,
            seatNumber = 198,
            last = "Koulumies",
            first = "Terhi",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Koulumies-Terhi-web-v7670-1389.JPG",
            twitter = "https://twitter.com/terhikoulumies",
            bornYear = 1971,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1345,
            seatNumber = 82,
            last = "Löfström",
            first = "Mats",
            party = "r",
            minister = false,
            picture = "attachment/member/pictures/Lofstrom-Mats-web-v7242-1345.JPG",
            twitter = "",
            bornYear = 1983,
            constituency = "Ahvenanmaa",
        ),
        MemberOfParliament(
            personNumber = 1265,
            seatNumber = 191,
            last = "Marttinen",
            first = "Matias",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Marttinen-Matias-web-v7302-1265.JPG",
            twitter = "",
            bornYear = 1990,
            constituency = "Satakunta",
        ),
        MemberOfParliament(
            personNumber = 1382,
            seatNumber = 139,
            last = "Mattila",
            first = "Hanna-Leena",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Mattila-Hanna-Leena-web-v6714-1382.JPG",
            twitter = "",
            bornYear = 1968,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1349,
            seatNumber = 89,
            last = "Meri",
            first = "Leena",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Meri-Leena-web-v6944-1349.jpg",
            twitter = "",
            bornYear = 1968,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1298,
            seatNumber = 47,
            last = "Mikkonen",
            first = "Krista",
            party = "vihr",
            minister = true,
            picture = "attachment/member/pictures/Mikkonen-Krista-web-v8248-1298.JPG",
            twitter = "",
            bornYear = 1972,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1299,
            seatNumber = 145,
            last = "Multala",
            first = "Sari",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Multala-Sari-web-v7954-1299.JPG",
            twitter = "",
            bornYear = 1978,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 802,
            seatNumber = 1,
            last = "Mustajärvi",
            first = "Markus",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Mustajarvi-Markus-web-v6810-802.JPG",
            twitter = "",
            bornYear = 1963,
            constituency = "Lappi",
        ),
        MemberOfParliament(
            personNumber = 1300,
            seatNumber = 147,
            last = "Mykkänen",
            first = "Kai",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Mykkanen-Kai-web-v7916-1300.JPG",
            twitter = "",
            bornYear = 1979,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1154,
            seatNumber = 18,
            last = "Myllykoski",
            first = "Jari",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Myllykoski-Jari-web-v8061-1154.JPG",
            twitter = "",
            bornYear = 1959,
            constituency = "Satakunta",
        ),
        MemberOfParliament(
            personNumber = 1437,
            seatNumber = 93,
            last = "Mäenpää",
            first = "Juha",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Maenpaa-Juha-web-v6990-1437.JPG",
            twitter = "",
            bornYear = 1971,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1301,
            seatNumber = 62,
            last = "Mäkelä",
            first = "Jani",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Makela-Jani-web-v7966-1301.JPG",
            twitter = "",
            bornYear = 1976,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1380,
            seatNumber = 132,
            last = "Mäkinen",
            first = "Riitta",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Makinen-Riitta-web-v7982-1380.JPG",
            twitter = "",
            bornYear = 1979,
            constituency = "Keski-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1087,
            seatNumber = 69,
            last = "Mäkisalo-Ropponen",
            first = "Merja",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Makisalo-Ropponen-Merja-web-v6908-1087.JPG",
            twitter = "",
            bornYear = 1958,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1438,
            seatNumber = 150,
            last = "Mäkynen",
            first = "Jukka",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Makynen-Jukka-web-v6663-1438.JPG",
            twitter = "",
            bornYear = 1961,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1469,
            seatNumber = 184,
            last = "Mäkynen",
            first = "Matias",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Makynen-Matias-web-v1248-1469.jpg",
            twitter = "",
            bornYear = 1990,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1418,
            seatNumber = 95,
            last = "Niemi",
            first = "Veijo",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Niemi-Veijo-web-v6558-1418.JPG",
            twitter = "",
            bornYear = 1954,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1092,
            seatNumber = 34,
            last = "Niikko",
            first = "Mika",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Niikko-Mika-web-v7871-1092.JPG",
            twitter = "",
            bornYear = 1967,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1440,
            seatNumber = 171,
            last = "Norrback",
            first = "Anders",
            party = "r",
            minister = false,
            picture = "attachment/member/pictures/Norrback-Anders-web-v6980-1440.JPG",
            twitter = "",
            bornYear = 1963,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1302,
            seatNumber = 99,
            last = "Nurminen",
            first = "Ilmari",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Nurminen-Ilmari-web-v7270-1302.JPG",
            twitter = "",
            bornYear = 1991,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1387,
            seatNumber = 164,
            last = "Ohisalo",
            first = "Maria",
            party = "vihr",
            minister = true,
            picture = "attachment/member/pictures/Ohisalo-Maria-web-v6852-1387.JPG",
            twitter = "https://twitter.com/MariaOhisalo",
            bornYear = 1985,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 971,
            seatNumber = 41,
            last = "Ojala-Niemelä",
            first = "Johanna",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Ojala-Niemela-Johanna-web-v8206-971.jpg",
            twitter = "",
            bornYear = 1974,
            constituency = "Lappi",
        ),
        MemberOfParliament(
            personNumber = 1441,
            seatNumber = 170,
            last = "Ollikainen",
            first = "Mikko",
            party = "r",
            minister = false,
            picture = "attachment/member/pictures/Ollikainen-Mikko-web-v6769-1441.JPG",
            twitter = "",
            bornYear = 1977,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 947,
            seatNumber = 57,
            last = "Orpo",
            first = "Petteri",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Orpo-Petteri-web-v8073-947.JPG",
            twitter = "",
            bornYear = 1969,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1422,
            seatNumber = 169,
            last = "Ovaska",
            first = "Jouni",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Ovaska-Jouni-web-v7015-1422.jpg",
            twitter = "",
            bornYear = 1986,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 887,
            seatNumber = 43,
            last = "Paatero",
            first = "Sirpa",
            party = "sd",
            minister = true,
            picture = "attachment/member/pictures/Paatero-Sirpa-web-v8230-887.JPG",
            twitter = "",
            bornYear = 1964,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1095,
            seatNumber = 178,
            last = "Packalén",
            first = "Tom",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Packalen-Tom-web-v7423-1095.JPG",
            twitter = "https://twitter.com/TomPackalen",
            bornYear = 1969,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1097,
            seatNumber = 40,
            last = "Pekonen",
            first = "Aino-Kaisa",
            party = "vas",
            minister = true,
            picture = "attachment/member/pictures/Pekonen-Aino-Kaisa-web-v7026-1097.JPG",
            twitter = "",
            bornYear = 1979,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1098,
            seatNumber = 118,
            last = "Pelkonen",
            first = "Jaana",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Pelkonen-Jaana-web-v7353-1098.JPG",
            twitter = "",
            bornYear = 1977,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1439,
            seatNumber = 181,
            last = "Peltokangas",
            first = "Mauri",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Peltokangas-Mauri-web-v6822-1439.JPG",
            twitter = "",
            bornYear = 1966,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1405,
            seatNumber = 165,
            last = "Petelius",
            first = "Pirkka-Pekka",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Petelius-Pirkka-Pekka-web-v7525-1405.JPG",
            twitter = "",
            bornYear = 1953,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1051,
            seatNumber = 103,
            last = "Piirainen",
            first = "Raimo",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Piirainen-Raimo-web-v7927-1051.JPG",
            twitter = "",
            bornYear = 1952,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1101,
            seatNumber = 79,
            last = "Pirttilahti",
            first = "Arto",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Pirttilahti-Arto-web-v7217-1101.JPG",
            twitter = "",
            bornYear = 1963,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1449,
            seatNumber = 188,
            last = "Pitko",
            first = "Jenni",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Pitko-Jenni-web-v7085-1449.JPG",
            twitter = "",
            bornYear = 1986,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1419,
            seatNumber = 125,
            last = "Puisto",
            first = "Sakari",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Puisto-Sakari-web-v6738-1419.JPG",
            twitter = "",
            bornYear = 1976,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1392,
            seatNumber = 120,
            last = "Purra",
            first = "Riikka",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Purra-Riikka-web-v7509-1392.JPG",
            twitter = "",
            bornYear = 1977,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1305,
            seatNumber = 109,
            last = "Pylväs",
            first = "Juha",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Pylvas-Juha-web-v7045-1305.JPG",
            twitter = "",
            bornYear = 1971,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1417,
            seatNumber = 124,
            last = "Ranne",
            first = "Lulu",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Ranne-Lulu-web-v4001-1417.jpg",
            twitter = "",
            bornYear = 1971,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1388,
            seatNumber = 92,
            last = "Rantanen",
            first = "Mari",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Rantanen-Mari-web-v6565-1388.JPG",
            twitter = "https://twitter.com/MariPSRantanen",
            bornYear = 1976,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1447,
            seatNumber = 161,
            last = "Rantanen",
            first = "Piritta",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Rantanen-Piritta-web-v7010-1447.JPG",
            twitter = "",
            bornYear = 1979,
            constituency = "Keski-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1374,
            seatNumber = 143,
            last = "Rehn-Kivi",
            first = "Veronica",
            party = "r",
            minister = false,
            picture = "attachment/member/pictures/Rehn-Kivi-Veronica-web-v7238-1374.JPG",
            twitter = "",
            bornYear = 1956,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1435,
            seatNumber = 91,
            last = "Reijonen",
            first = "Minna",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Reijonen-Minna-web-v6684-1435.JPG",
            twitter = "",
            bornYear = 1972,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1274,
            seatNumber = 45,
            last = "Rinne",
            first = "Antti",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Rinne-Antti-web-v7738-1274.JPG",
            twitter = "",
            bornYear = 1962,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 809,
            seatNumber = 11,
            last = "Risikko",
            first = "Paula",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Risikko-Paula-web-v8023-809.JPG",
            twitter = "",
            bornYear = 1960,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1308,
            seatNumber = 38,
            last = "Ronkainen",
            first = "Jari",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Ronkainen-Jari-web-v7440-1308.JPG",
            twitter = "",
            bornYear = 1972,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1282,
            seatNumber = 173,
            last = "Rydman",
            first = "Wille",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Rydman-Wille-web-v7654-1282.JPG",
            twitter = "https://twitter.com/willerydman",
            bornYear = 1986,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 499,
            seatNumber = 30,
            last = "Räsänen",
            first = "Päivi",
            party = "kd",
            minister = false,
            picture = "attachment/member/pictures/Rasanen-Paivi-web-v7313-499.JPG",
            twitter = "",
            bornYear = 1959,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1157,
            seatNumber = 77,
            last = "Saarikko",
            first = "Annika",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Saarikko-Annika-web-v8398-1157.JPG",
            twitter = "",
            bornYear = 1983,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1102,
            seatNumber = 68,
            last = "Salonen",
            first = "Kristiina",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Salonen-Kristiina-web-v7940-1102.JPG",
            twitter = "",
            bornYear = 1977,
            constituency = "Satakunta",
        ),
        MemberOfParliament(
            personNumber = 1105,
            seatNumber = 146,
            last = "Sankelo",
            first = "Janne",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Sankelo-Janne-web-v7407-1105.JPG",
            twitter = "",
            bornYear = 1967,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1400,
            seatNumber = 157,
            last = "Saramo",
            first = "Jussi",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Saramo-Jussi-web-v6898-1400.JPG",
            twitter = "",
            bornYear = 1979,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1312,
            seatNumber = 65,
            last = "Sarkkinen",
            first = "Hanna",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Sarkkinen-Hanna-web-v7035-1312.JPG",
            twitter = "",
            bornYear = 1988,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 612,
            seatNumber = 32,
            last = "Sarkomaa",
            first = "Sari",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Sarkomaa-Sari-web-v7589-612.JPG",
            twitter = "https://twitter.com/sarisarkomaa",
            bornYear = 1965,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 784,
            seatNumber = 13,
            last = "Satonen",
            first = "Arto",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Satonen-Arto-web-v7571-784.JPG",
            twitter = "",
            bornYear = 1966,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1314,
            seatNumber = 36,
            last = "Savio",
            first = "Sami",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Savio-Sami-web-v8201-1314.JPG",
            twitter = "",
            bornYear = 1975,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1106,
            seatNumber = 81,
            last = "Savola",
            first = "Mikko",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Savola-Mikko-web-v7212-1106.JPG",
            twitter = "",
            bornYear = 1981,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1315,
            seatNumber = 98,
            last = "Semi",
            first = "Matti",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Semi-Matti-web-v7319-1315.JPG",
            twitter = "",
            bornYear = 1957,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1450,
            seatNumber = 155,
            last = "Simula",
            first = "Jenna",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Simula-Jenna-web-v8321-1450.JPG",
            twitter = "",
            bornYear = 1989,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1108,
            seatNumber = 78,
            last = "Sipilä",
            first = "Juha",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Sipila-Juha-web-v8346-1108.JPG",
            twitter = "",
            bornYear = 1961,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1219,
            seatNumber = 172,
            last = "Sirén",
            first = "Saara-Sofia",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Siren-Saara-Sofia-web-v8034-1219.JPG",
            twitter = "",
            bornYear = 1986,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1395,
            seatNumber = 196,
            last = "Sjöblom",
            first = "Ruut",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Sjoblom-Ruut-web-v7842-1395.JPG",
            twitter = "",
            bornYear = 1976,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1316,
            seatNumber = 133,
            last = "Skinnari",
            first = "Ville",
            party = "sd",
            minister = true,
            picture = "attachment/member/pictures/Skinnari-Ville-web-v8115-1316.JPG",
            twitter = "",
            bornYear = 1974,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1393,
            seatNumber = 123,
            last = "Slunga-Poutsalo",
            first = "Riikka",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Slunga-Poutsalo-Riikka-web-v6591-1393.JPG",
            twitter = "",
            bornYear = 1971,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1416,
            seatNumber = 185,
            last = "Soinikoski",
            first = "Mirka",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Soinikoski-Mirka-web-v7505-1416.jpg",
            twitter = "",
            bornYear = 1975,
            constituency = "Häme",
        ),
        MemberOfParliament(
            personNumber = 1318,
            seatNumber = 113,
            last = "Strand",
            first = "Joakim",
            party = "r",
            minister = false,
            picture = "attachment/member/pictures/Strand-Joakim-web-v7474-1318.JPG",
            twitter = "",
            bornYear = 1982,
            constituency = "Vaasa",
        ),
        MemberOfParliament(
            personNumber = 1423,
            seatNumber = 186,
            last = "Suomela",
            first = "Iiris",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Suomela-Iiris-web-v7058-1423.JPG",
            twitter = "",
            bornYear = 1994,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 952,
            seatNumber = 74,
            last = "Taimela",
            first = "Katja",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Taimela-Katja-web-v7890-952.JPG",
            twitter = "",
            bornYear = 1974,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1323,
            seatNumber = 176,
            last = "Talvitie",
            first = "Mari-Leena",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Talvitie-Mari-Leena-web-v8307-1323.JPG",
            twitter = "",
            bornYear = 1980,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1325,
            seatNumber = 114,
            last = "Tanus",
            first = "Sari",
            party = "kd",
            minister = false,
            picture = "attachment/member/pictures/Tanus-Sari-web-v8139-1325.JPG",
            twitter = "",
            bornYear = 1964,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1327,
            seatNumber = 61,
            last = "Tavio",
            first = "Ville",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Tavio-Ville-web-v6791-1327.JPG",
            twitter = "",
            bornYear = 1984,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1118,
            seatNumber = 86,
            last = "Tolvanen",
            first = "Kari",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Tolvanen-Kari-web-v7852-1118.JPG",
            twitter = "",
            bornYear = 1961,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1120,
            seatNumber = 48,
            last = "Torniainen",
            first = "Ari",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Torniainen-Ari-web-v7141-1120.JPG",
            twitter = "",
            bornYear = 1956,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 357,
            seatNumber = 5,
            last = "Tuomioja",
            first = "Erkki",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Tuomioja-Erkki-web-v7682-357.JPG",
            twitter = "https://twitter.com/TuomiojaErkki",
            bornYear = 1946,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1126,
            seatNumber = 104,
            last = "Tuppurainen",
            first = "Tytti",
            party = "sd",
            minister = true,
            picture = "attachment/member/pictures/Tuppurainen-Tytti-web-v7780-1126.jpg",
            twitter = "",
            bornYear = 1976,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1427,
            seatNumber = 179,
            last = "Turtiainen",
            first = "Ano",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Turtiainen-Ano-web-v0279-1427.jpg",
            twitter = "",
            bornYear = 1967,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1451,
            seatNumber = 126,
            last = "Tynkkynen",
            first = "Sebastian",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Tynkkynen-Sebastian-web-v6751-1451.JPG",
            twitter = "",
            bornYear = 1989,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 1420,
            seatNumber = 180,
            last = "Vallin",
            first = "Veikko",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Vallin-Veikko-web-v6801-1420.JPG",
            twitter = "",
            bornYear = 1962,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1131,
            seatNumber = 119,
            last = "Wallinheimo",
            first = "Sinuhe",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Wallinheimo-Sinuhe-web-v7517-1131.JPG",
            twitter = "",
            bornYear = 1972,
            constituency = "Keski-Suomi",
        ),
        MemberOfParliament(
            personNumber = 414,
            seatNumber = 8,
            last = "Vanhanen",
            first = "Matti",
            party = "kesk",
            minister = true,
            picture = "attachment/member/pictures/Vanhanen-Matti-web-v7828-414.JPG",
            twitter = "",
            bornYear = 1955,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1330,
            seatNumber = 148,
            last = "Vartiainen",
            first = "Juhana",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Vartiainen-Juhana-web-v7327-1330.JPG",
            twitter = "https://twitter.com/filsdeproust",
            bornYear = 1958,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 508,
            seatNumber = 0,
            last = "Vehviläinen",
            first = "Anu",
            party = "kesk",
            minister = false,
            picture = "attachment/member/pictures/Vehvilainen-Anu-web-v8263-508.JPG",
            twitter = "",
            bornYear = 1963,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1429,
            seatNumber = 183,
            last = "Werning",
            first = "Paula",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Werning-Paula-web-v8235-1429.JPG",
            twitter = "",
            bornYear = 1976,
            constituency = "Kaakkois-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1396,
            seatNumber = 193,
            last = "Vestman",
            first = "Heikki",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Vestman-Heikki-web-v7365-1396.JPG",
            twitter = "",
            bornYear = 1985,
            constituency = "Uusimaa",
        ),
        MemberOfParliament(
            personNumber = 1436,
            seatNumber = 121,
            last = "Wihonen",
            first = "Jussi",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Wihonen-Jussi-web-v6580-1436.JPG",
            twitter = "",
            bornYear = 1963,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 511,
            seatNumber = 22,
            last = "Viitanen",
            first = "Pia",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Viitanen-Pia-web-v7116-511.JPG",
            twitter = "",
            bornYear = 1967,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1134,
            seatNumber = 117,
            last = "Vikman",
            first = "Sofia",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Vikman-Sofia-web-v1234-1134.jpg",
            twitter = "",
            bornYear = 1983,
            constituency = "Pirkanmaa",
        ),
        MemberOfParliament(
            personNumber = 1414,
            seatNumber = 182,
            last = "Viljanen",
            first = "Heidi",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Viljanen-Heidi-web-v7713-1414.JPG",
            twitter = "",
            bornYear = 1980,
            constituency = "Satakunta",
        ),
        MemberOfParliament(
            personNumber = 948,
            seatNumber = 33,
            last = "Virolainen",
            first = "Anne-Mari",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Virolainen-Anne-Mari-web-v8007-948.JPG",
            twitter = "",
            bornYear = 1965,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1411,
            seatNumber = 187,
            last = "Virta",
            first = "Sofia",
            party = "vihr",
            minister = false,
            picture = "attachment/member/pictures/Virta-Sofia-web-v7624-1411.JPG",
            twitter = "",
            bornYear = 1990,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 1136,
            seatNumber = 35,
            last = "Vähämäki",
            first = "Ville",
            party = "ps",
            minister = false,
            picture = "attachment/member/pictures/Vahamaki-Ville-web-v8334-1136.JPG",
            twitter = "",
            bornYear = 1979,
            constituency = "Oulu",
        ),
        MemberOfParliament(
            personNumber = 794,
            seatNumber = 73,
            last = "Väätäinen",
            first = "Tuula",
            party = "sd",
            minister = false,
            picture = "attachment/member/pictures/Vaatainen-Tuula-web-v6831-794.JPG",
            twitter = "",
            bornYear = 1955,
            constituency = "Savo-Karjala",
        ),
        MemberOfParliament(
            personNumber = 1407,
            seatNumber = 156,
            last = "Yrttiaho",
            first = "Johannes",
            party = "vas",
            minister = false,
            picture = "attachment/member/pictures/Yrttiaho-Johannes-web-v7543-1407.JPG",
            twitter = "",
            bornYear = 1980,
            constituency = "Varsinais-Suomi",
        ),
        MemberOfParliament(
            personNumber = 301,
            seatNumber = 56,
            last = "Zyskowicz",
            first = "Ben",
            party = "kok",
            minister = false,
            picture = "attachment/member/pictures/Zyskowicz-Ben-web-v7674-301.JPG",
            twitter = "",
            bornYear = 1954,
            constituency = "Helsinki",
        ),
        MemberOfParliament(
            personNumber = 1141,
            seatNumber = 84,
            last = "Östman",
            first = "Peter",
            party = "kd",
            minister = false,
            picture = "attachment/member/pictures/Ostman-Peter-web-v8290-1141.JPG",
            twitter = "",
            bornYear = 1961,
            constituency = "Vaasa",
        ),
    )
}
